# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LocationBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='templates.Block')),
                ('westLong', models.DecimalField(decimal_places=3, default=-180, max_digits=6)),
                ('eastLong', models.DecimalField(decimal_places=3, default=180, max_digits=6)),
                ('northLat', models.DecimalField(decimal_places=3, default=90, max_digits=6)),
                ('southLat', models.DecimalField(decimal_places=3, default=-90, max_digits=6)),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('templates.block',),
        ),
        migrations.CreateModel(
            name='MeasurementBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='templates.Block')),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('measurement', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('templates.block',),
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='templates.Block')),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('templates.block',),
        ),
        migrations.AddField(
            model_name='template',
            name='blocks',
            field=models.ManyToManyField(blank=True, to='templates.Block'),
        ),
        migrations.AddField(
            model_name='block',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_templates.block_set+', to='contenttypes.ContentType'),
        ),
    ]
