# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='blocks',
        ),
        migrations.AddField(
            model_name='block',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='templates.Template'),
        ),
        migrations.AddField(
            model_name='template',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
