# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_auto_20181028_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('template', models.ManyToManyField(to='templates.Template')),
            ],
        ),
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
